# Generated by Django 3.2 on 2022-05-26 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_usernew_numphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zakaz_goods_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zakaz_goods_id', to='Main.goods')),
                ('zakaz_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zakaz_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_goods_id', to='Main.goods')),
                ('cart_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
