# Generated by Django 3.2 on 2022-05-31 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_zakaz_zakaz_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='zakaz_type',
            field=models.CharField(blank=True, choices=[('1', 'На расмотрении'), ('2', 'Отклонено'), ('3', 'Закрыт')], default='1', max_length=300, null=True),
        ),
    ]
