# Generated by Django 3.2 on 2022-05-31 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_zakaz_zakaz_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zakaz',
            old_name='zakaz_type',
            new_name='zakaz_status',
        ),
    ]
