# Generated by Django 3.2 on 2022-06-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_rename_zakaz_type_zakaz_zakaz_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_goods_count',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
