# Generated by Django 3.2 on 2022-06-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_cart_cart_goods_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='zakaz_time',
            field=models.DateTimeField(verbose_name='время добавление'),
        ),
    ]
