# Generated by Django 3.2 on 2022-06-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_alter_zakaz_zakaz_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_goods_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во'),
        ),
    ]
