# Generated by Django 3.2 on 2022-06-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_alter_cart_cart_goods_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='zakaz_goods_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во'),
        ),
    ]
