# Generated by Django 3.2 on 2022-06-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_zakaz_zakaz_goods_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='zakaz_status',
            field=models.CharField(blank=True, choices=[('1', 'На расмотрении'), ('2', 'Отклонено'), ('3', 'Одобренно')], default='1', max_length=300, null=True),
        ),
    ]
